// <auto-generated />
using AssetDistributionWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssetDistributionWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220308060601_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AssetDistributionWebApp.Models.assets", b =>
                {
                    b.Property<int>("assetid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("focalPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("assetid");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("AssetDistributionWebApp.Models.distribution", b =>
                {
                    b.Property<int>("distributionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("approved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("assetid")
                        .HasColumnType("int");

                    b.Property<string>("useremail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("distributionid");

                    b.HasIndex("assetid");

                    b.ToTable("distributions");
                });

            modelBuilder.Entity("AssetDistributionWebApp.Models.distribution", b =>
                {
                    b.HasOne("AssetDistributionWebApp.Models.assets", "assets")
                        .WithMany()
                        .HasForeignKey("assetid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assets");
                });
#pragma warning restore 612, 618
        }
    }
}
